// Code generated by goctl. DO NOT EDIT.
// Source: trade.proto

package tradeserver

import (
	"context"

	"trade/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TradeExecutionResp = pb.TradeExecutionResp
	TradeListResp      = pb.TradeListResp
	TradeOnceResp      = pb.TradeOnceResp
	TradeOrderIdReq    = pb.TradeOrderIdReq
	TradeReq           = pb.TradeReq

	TradeServer interface {
		GetTradeList(ctx context.Context, in *TradeOrderIdReq, opts ...grpc.CallOption) (*TradeListResp, error)
		TradeExecution(ctx context.Context, in *TradeReq, opts ...grpc.CallOption) (*TradeExecutionResp, error)
	}

	defaultTradeServer struct {
		cli zrpc.Client
	}
)

func NewTradeServer(cli zrpc.Client) TradeServer {
	return &defaultTradeServer{
		cli: cli,
	}
}

func (m *defaultTradeServer) GetTradeList(ctx context.Context, in *TradeOrderIdReq, opts ...grpc.CallOption) (*TradeListResp, error) {
	client := pb.NewTradeServerClient(m.cli.Conn())
	return client.GetTradeList(ctx, in, opts...)
}

func (m *defaultTradeServer) TradeExecution(ctx context.Context, in *TradeReq, opts ...grpc.CallOption) (*TradeExecutionResp, error) {
	client := pb.NewTradeServerClient(m.cli.Conn())
	return client.TradeExecution(ctx, in, opts...)
}
