// Code generated by goctl. DO NOT EDIT.
// Source: trade.proto

package server

import (
	"context"
	"trade/internal/logic"
	"trade/internal/svc"
	"trade/pb"
)

type GsfServerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTradeServerServer
}

func NewGsfServerServer(svcCtx *svc.ServiceContext) *GsfServerServer {
	return &GsfServerServer{
		svcCtx: svcCtx,
	}
}

func (s *GsfServerServer) GetTradeList(ctx context.Context, in *pb.TradeOrderIdReq) (*pb.TradeListResp, error) {
	l := logic.NewGetTradeListLogic(ctx, s.svcCtx)
	return l.GetTradeList(in)
}

func (s *GsfServerServer) TradeExecution(ctx context.Context, in *pb.TradeReq) (*pb.TradeExecutionResp, error) {
	l := logic.NewTradeExecutionLogic(ctx, s.svcCtx)
	return l.TradeExecution(in)
}
