// Code generated by goctl. DO NOT EDIT.
// Source: trade.proto

package server

import (
	"context"

	"trade/internal/logic"
	"trade/internal/svc"
	"trade/pb"
)

type TradeServerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTradeServerServer
}

func NewTradeServerServer(svcCtx *svc.ServiceContext) *TradeServerServer {
	return &TradeServerServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeServerServer) GetTradeList(ctx context.Context, in *pb.TradeOrderIdReq) (*pb.TradeListResp, error) {
	l := logic.NewGetTradeListLogic(ctx, s.svcCtx)
	return l.GetTradeList(in)
}

func (s *TradeServerServer) TradeExecution(ctx context.Context, in *pb.TradeReq) (*pb.TradeExecutionResp, error) {
	l := logic.NewTradeExecutionLogic(ctx, s.svcCtx)
	return l.TradeExecution(in)
}
