// Code generated by goctl. DO NOT EDIT.
// Source: trade.proto

package server

import (
	"context"

	"trade/internal/logic"
	"trade/internal/svc"
	"trade/pb"
)

type TradeServerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTradeServerServer
}

func NewTradeServerServer(svcCtx *svc.ServiceContext) *TradeServerServer {
	return &TradeServerServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeServerServer) GetAllTradeOrderObtainList(ctx context.Context, in *pb.GetAllTradeOrderObtainReq) (*pb.TradeListResp, error) {
	l := logic.NewGetAllTradeOrderObtainListLogic(ctx, s.svcCtx)
	return l.GetAllTradeOrderObtainList(in)
}

func (s *TradeServerServer) GetTradeObtainList(ctx context.Context, in *pb.TradeObtainReq) (*pb.TradeListResp, error) {
	l := logic.NewGetTradeObtainListLogic(ctx, s.svcCtx)
	return l.GetTradeObtainList(in)
}

func (s *TradeServerServer) TradeExecution(ctx context.Context, in *pb.TradeReq) (*pb.TradeExecutionResp, error) {
	l := logic.NewTradeExecutionLogic(ctx, s.svcCtx)
	return l.TradeExecution(in)
}

func (s *TradeServerServer) TradeOrderUpdate(ctx context.Context, in *pb.TradeOrderUpdateReq) (*pb.TradeOrderUpdateResp, error) {
	l := logic.NewTradeOrderUpdateLogic(ctx, s.svcCtx)
	return l.TradeOrderUpdate(in)
}
