// Code generated by goctl. DO NOT EDIT.
package types

type Ping struct {
	Message string `json:"message"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Passowrd string `json:"passowrd"`
}

type LoginResponse struct {
	JwtToken string `json:"token"`
}

type ChineseTemplateRequestItem struct {
	Title string `json:"title"`
	Desc  string `json:"desc"`
}

type ChineseTemplateRequest struct {
	GID     string                        `json:"gid"`
	Titile  string                        `json:"titile"`
	Item    []*ChineseTemplateRequestItem `json:"item"`
	ImgList []string                      `json:"img_list"`
}

type ChineseTemplateResponse struct {
}
