// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	gsf_back "gsf/internal/handler/gsf_back"
	"gsf/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/ping",
					Handler: pingHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/gsf_back/login",
					Handler: gsf_back.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/gsf_back/chinese_template",
					Handler: gsf_back.ChineseTemplateHandler(serverCtx),
				},
			}...,
		),
	)
}
