// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: pb/proto/pay.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskToken string `protobuf:"bytes,1,opt,name=TaskToken,proto3" json:"TaskToken,omitempty"`
	ReqTime   string `protobuf:"bytes,2,opt,name=ReqTime,proto3" json:"ReqTime,omitempty"`
}

func (x *PayReq) Reset() {
	*x = PayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReq) ProtoMessage() {}

func (x *PayReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReq.ProtoReflect.Descriptor instead.
func (*PayReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{0}
}

func (x *PayReq) GetTaskToken() string {
	if x != nil {
		return x.TaskToken
	}
	return ""
}

func (x *PayReq) GetReqTime() string {
	if x != nil {
		return x.ReqTime
	}
	return ""
}

type PayOnceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayOrderId string `protobuf:"bytes,1,opt,name=PayOrderId,proto3" json:"PayOrderId,omitempty"`
}

func (x *PayOnceReq) Reset() {
	*x = PayOnceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOnceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOnceReq) ProtoMessage() {}

func (x *PayOnceReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOnceReq.ProtoReflect.Descriptor instead.
func (*PayOnceReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{1}
}

func (x *PayOnceReq) GetPayOrderId() string {
	if x != nil {
		return x.PayOrderId
	}
	return ""
}

type PayOnceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayOrderId    string `protobuf:"bytes,1,opt,name=PayOrderId,proto3" json:"PayOrderId,omitempty"`
	Initiator     string `protobuf:"bytes,2,opt,name=Initiator,proto3" json:"Initiator,omitempty"`
	Recipient     string `protobuf:"bytes,3,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	PayStatus     int32  `protobuf:"varint,4,opt,name=PayStatus,proto3" json:"PayStatus,omitempty"`
	PayAmount     int64  `protobuf:"varint,5,opt,name=PayAmount,proto3" json:"PayAmount,omitempty"`
	InitiatorTime string `protobuf:"bytes,6,opt,name=InitiatorTime,proto3" json:"InitiatorTime,omitempty"`
	FinishTime    string `protobuf:"bytes,7,opt,name=FinishTime,proto3" json:"FinishTime,omitempty"`
}

func (x *PayOnceResp) Reset() {
	*x = PayOnceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOnceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOnceResp) ProtoMessage() {}

func (x *PayOnceResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOnceResp.ProtoReflect.Descriptor instead.
func (*PayOnceResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{2}
}

func (x *PayOnceResp) GetPayOrderId() string {
	if x != nil {
		return x.PayOrderId
	}
	return ""
}

func (x *PayOnceResp) GetInitiator() string {
	if x != nil {
		return x.Initiator
	}
	return ""
}

func (x *PayOnceResp) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *PayOnceResp) GetPayStatus() int32 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *PayOnceResp) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *PayOnceResp) GetInitiatorTime() string {
	if x != nil {
		return x.InitiatorTime
	}
	return ""
}

func (x *PayOnceResp) GetFinishTime() string {
	if x != nil {
		return x.FinishTime
	}
	return ""
}

type PayListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayListResp []*PayOnceResp `protobuf:"bytes,1,rep,name=PayListResp,proto3" json:"PayListResp,omitempty"`
}

func (x *PayListResp) Reset() {
	*x = PayListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayListResp) ProtoMessage() {}

func (x *PayListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayListResp.ProtoReflect.Descriptor instead.
func (*PayListResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{3}
}

func (x *PayListResp) GetPayListResp() []*PayOnceResp {
	if x != nil {
		return x.PayListResp
	}
	return nil
}

type PayExecutionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayOrderId string `protobuf:"bytes,1,opt,name=PayOrderId,proto3" json:"PayOrderId,omitempty"`
	PayStatus  int32  `protobuf:"varint,2,opt,name=PayStatus,proto3" json:"PayStatus,omitempty"`
	CreateTime string `protobuf:"bytes,3,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
}

func (x *PayExecutionResp) Reset() {
	*x = PayExecutionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayExecutionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayExecutionResp) ProtoMessage() {}

func (x *PayExecutionResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayExecutionResp.ProtoReflect.Descriptor instead.
func (*PayExecutionResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{4}
}

func (x *PayExecutionResp) GetPayOrderId() string {
	if x != nil {
		return x.PayOrderId
	}
	return ""
}

func (x *PayExecutionResp) GetPayStatus() int32 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *PayExecutionResp) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type PayApproveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayOrderId string `protobuf:"bytes,1,opt,name=PayOrderId,proto3" json:"PayOrderId,omitempty"`
}

func (x *PayApproveReq) Reset() {
	*x = PayApproveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayApproveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayApproveReq) ProtoMessage() {}

func (x *PayApproveReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayApproveReq.ProtoReflect.Descriptor instead.
func (*PayApproveReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{5}
}

func (x *PayApproveReq) GetPayOrderId() string {
	if x != nil {
		return x.PayOrderId
	}
	return ""
}

type PayApproveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayStatus string `protobuf:"bytes,1,opt,name=PayStatus,proto3" json:"PayStatus,omitempty"`
}

func (x *PayApproveResp) Reset() {
	*x = PayApproveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayApproveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayApproveResp) ProtoMessage() {}

func (x *PayApproveResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayApproveResp.ProtoReflect.Descriptor instead.
func (*PayApproveResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{6}
}

func (x *PayApproveResp) GetPayStatus() string {
	if x != nil {
		return x.PayStatus
	}
	return ""
}

type PayOrderStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayOrderId string `protobuf:"bytes,1,opt,name=PayOrderId,proto3" json:"PayOrderId,omitempty"`
}

func (x *PayOrderStatusReq) Reset() {
	*x = PayOrderStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOrderStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderStatusReq) ProtoMessage() {}

func (x *PayOrderStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderStatusReq.ProtoReflect.Descriptor instead.
func (*PayOrderStatusReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{7}
}

func (x *PayOrderStatusReq) GetPayOrderId() string {
	if x != nil {
		return x.PayOrderId
	}
	return ""
}

type PayOrderStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	TTL    int32  `protobuf:"varint,2,opt,name=TTL,proto3" json:"TTL,omitempty"`
	PayID  string `protobuf:"bytes,3,opt,name=PayID,proto3" json:"PayID,omitempty"`
	Status string `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *PayOrderStatusResp) Reset() {
	*x = PayOrderStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_pay_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOrderStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderStatusResp) ProtoMessage() {}

func (x *PayOrderStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_pay_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderStatusResp.ProtoReflect.Descriptor instead.
func (*PayOrderStatusResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_pay_proto_rawDescGZIP(), []int{8}
}

func (x *PayOrderStatusResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PayOrderStatusResp) GetTTL() int32 {
	if x != nil {
		return x.TTL
	}
	return 0
}

func (x *PayOrderStatusResp) GetPayID() string {
	if x != nil {
		return x.PayID
	}
	return ""
}

func (x *PayOrderStatusResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pb_proto_pay_proto protoreflect.FileDescriptor

var file_pb_proto_pay_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x40, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x52, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x0a, 0x50, 0x61,
	0x79, 0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0xeb, 0x01, 0x0a, 0x0b, 0x50, 0x61, 0x79,
	0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50, 0x61, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74,
	0x6f, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x61, 0x79, 0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0b, 0x50, 0x61, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x70, 0x0a, 0x10, 0x50, 0x61, 0x79, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a,
	0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x0d, 0x50, 0x61,
	0x79, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x50,
	0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x0e, 0x50,
	0x61, 0x79, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x33, 0x0a, 0x11, 0x50,
	0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x68, 0x0a, 0x12, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x54,
	0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x54, 0x54, 0x4c, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x61, 0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x61, 0x79,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xe2, 0x01, 0x0a, 0x09, 0x50,
	0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x4f,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0c, 0x50, 0x61, 0x79, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x50, 0x61, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x50, 0x61,
	0x79, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61,
	0x79, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x61, 0x79, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_proto_pay_proto_rawDescOnce sync.Once
	file_pb_proto_pay_proto_rawDescData = file_pb_proto_pay_proto_rawDesc
)

func file_pb_proto_pay_proto_rawDescGZIP() []byte {
	file_pb_proto_pay_proto_rawDescOnce.Do(func() {
		file_pb_proto_pay_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_pay_proto_rawDescData)
	})
	return file_pb_proto_pay_proto_rawDescData
}

var file_pb_proto_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_proto_pay_proto_goTypes = []interface{}{
	(*PayReq)(nil),             // 0: pb.PayReq
	(*PayOnceReq)(nil),         // 1: pb.PayOnceReq
	(*PayOnceResp)(nil),        // 2: pb.PayOnceResp
	(*PayListResp)(nil),        // 3: pb.PayListResp
	(*PayExecutionResp)(nil),   // 4: pb.PayExecutionResp
	(*PayApproveReq)(nil),      // 5: pb.PayApproveReq
	(*PayApproveResp)(nil),     // 6: pb.PayApproveResp
	(*PayOrderStatusReq)(nil),  // 7: pb.PayOrderStatusReq
	(*PayOrderStatusResp)(nil), // 8: pb.PayOrderStatusResp
}
var file_pb_proto_pay_proto_depIdxs = []int32{
	2, // 0: pb.PayListResp.PayListResp:type_name -> pb.PayOnceResp
	1, // 1: pb.PayServer.GetPayList:input_type -> pb.PayOnceReq
	0, // 2: pb.PayServer.PayExecution:input_type -> pb.PayReq
	7, // 3: pb.PayServer.PayOrderStatus:input_type -> pb.PayOrderStatusReq
	5, // 4: pb.PayServer.PayApprove:input_type -> pb.PayApproveReq
	3, // 5: pb.PayServer.GetPayList:output_type -> pb.PayListResp
	4, // 6: pb.PayServer.PayExecution:output_type -> pb.PayExecutionResp
	8, // 7: pb.PayServer.PayOrderStatus:output_type -> pb.PayOrderStatusResp
	6, // 8: pb.PayServer.PayApprove:output_type -> pb.PayApproveResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_proto_pay_proto_init() }
func file_pb_proto_pay_proto_init() {
	if File_pb_proto_pay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_pay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_pay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOnceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_pay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOnceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_pay_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_pay_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayExecutionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_pay_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayApproveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_pay_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayApproveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_pay_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOrderStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_pay_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOrderStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_pay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_proto_pay_proto_goTypes,
		DependencyIndexes: file_pb_proto_pay_proto_depIdxs,
		MessageInfos:      file_pb_proto_pay_proto_msgTypes,
	}.Build()
	File_pb_proto_pay_proto = out.File
	file_pb_proto_pay_proto_rawDesc = nil
	file_pb_proto_pay_proto_goTypes = nil
	file_pb_proto_pay_proto_depIdxs = nil
}
