// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: proto/proto/trade.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TradeServer_GetAllTradeOrderObtainList_FullMethodName = "/proto.TradeServer/GetAllTradeOrderObtainList"
	TradeServer_GetTradeObtainList_FullMethodName         = "/proto.TradeServer/GetTradeObtainList"
	TradeServer_TradeExecution_FullMethodName             = "/proto.TradeServer/TradeExecution"
	TradeServer_TradeOrderUpdate_FullMethodName           = "/proto.TradeServer/TradeOrderUpdate"
)

// TradeServerClient is the client API for TradeServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeServerClient interface {
	GetAllTradeOrderObtainList(ctx context.Context, in *GetAllTradeOrderObtainReq, opts ...grpc.CallOption) (*TradeListResp, error)
	GetTradeObtainList(ctx context.Context, in *TradeObtainReq, opts ...grpc.CallOption) (*TradeListResp, error)
	TradeExecution(ctx context.Context, in *TradeReq, opts ...grpc.CallOption) (*TradeExecutionResp, error)
	TradeOrderUpdate(ctx context.Context, in *TradeOrderUpdateReq, opts ...grpc.CallOption) (*TradeOrderUpdateResp, error)
}

type tradeServerClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeServerClient(cc grpc.ClientConnInterface) TradeServerClient {
	return &tradeServerClient{cc}
}

func (c *tradeServerClient) GetAllTradeOrderObtainList(ctx context.Context, in *GetAllTradeOrderObtainReq, opts ...grpc.CallOption) (*TradeListResp, error) {
	out := new(TradeListResp)
	err := c.cc.Invoke(ctx, TradeServer_GetAllTradeOrderObtainList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServerClient) GetTradeObtainList(ctx context.Context, in *TradeObtainReq, opts ...grpc.CallOption) (*TradeListResp, error) {
	out := new(TradeListResp)
	err := c.cc.Invoke(ctx, TradeServer_GetTradeObtainList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServerClient) TradeExecution(ctx context.Context, in *TradeReq, opts ...grpc.CallOption) (*TradeExecutionResp, error) {
	out := new(TradeExecutionResp)
	err := c.cc.Invoke(ctx, TradeServer_TradeExecution_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServerClient) TradeOrderUpdate(ctx context.Context, in *TradeOrderUpdateReq, opts ...grpc.CallOption) (*TradeOrderUpdateResp, error) {
	out := new(TradeOrderUpdateResp)
	err := c.cc.Invoke(ctx, TradeServer_TradeOrderUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeServerServer is the server API for TradeServer service.
// All implementations must embed UnimplementedTradeServerServer
// for forward compatibility
type TradeServerServer interface {
	GetAllTradeOrderObtainList(context.Context, *GetAllTradeOrderObtainReq) (*TradeListResp, error)
	GetTradeObtainList(context.Context, *TradeObtainReq) (*TradeListResp, error)
	TradeExecution(context.Context, *TradeReq) (*TradeExecutionResp, error)
	TradeOrderUpdate(context.Context, *TradeOrderUpdateReq) (*TradeOrderUpdateResp, error)
	mustEmbedUnimplementedTradeServerServer()
}

// UnimplementedTradeServerServer must be embedded to have forward compatible implementations.
type UnimplementedTradeServerServer struct {
}

func (UnimplementedTradeServerServer) GetAllTradeOrderObtainList(context.Context, *GetAllTradeOrderObtainReq) (*TradeListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTradeOrderObtainList not implemented")
}
func (UnimplementedTradeServerServer) GetTradeObtainList(context.Context, *TradeObtainReq) (*TradeListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTradeObtainList not implemented")
}
func (UnimplementedTradeServerServer) TradeExecution(context.Context, *TradeReq) (*TradeExecutionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeExecution not implemented")
}
func (UnimplementedTradeServerServer) TradeOrderUpdate(context.Context, *TradeOrderUpdateReq) (*TradeOrderUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeOrderUpdate not implemented")
}
func (UnimplementedTradeServerServer) mustEmbedUnimplementedTradeServerServer() {}

// UnsafeTradeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeServerServer will
// result in compilation errors.
type UnsafeTradeServerServer interface {
	mustEmbedUnimplementedTradeServerServer()
}

func RegisterTradeServerServer(s grpc.ServiceRegistrar, srv TradeServerServer) {
	s.RegisterService(&TradeServer_ServiceDesc, srv)
}

func _TradeServer_GetAllTradeOrderObtainList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTradeOrderObtainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServerServer).GetAllTradeOrderObtainList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeServer_GetAllTradeOrderObtainList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServerServer).GetAllTradeOrderObtainList(ctx, req.(*GetAllTradeOrderObtainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeServer_GetTradeObtainList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeObtainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServerServer).GetTradeObtainList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeServer_GetTradeObtainList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServerServer).GetTradeObtainList(ctx, req.(*TradeObtainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeServer_TradeExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServerServer).TradeExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeServer_TradeExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServerServer).TradeExecution(ctx, req.(*TradeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeServer_TradeOrderUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeOrderUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServerServer).TradeOrderUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeServer_TradeOrderUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServerServer).TradeOrderUpdate(ctx, req.(*TradeOrderUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeServer_ServiceDesc is the grpc.ServiceDesc for TradeServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TradeServer",
	HandlerType: (*TradeServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTradeOrderObtainList",
			Handler:    _TradeServer_GetAllTradeOrderObtainList_Handler,
		},
		{
			MethodName: "GetTradeObtainList",
			Handler:    _TradeServer_GetTradeObtainList_Handler,
		},
		{
			MethodName: "TradeExecution",
			Handler:    _TradeServer_TradeExecution_Handler,
		},
		{
			MethodName: "TradeOrderUpdate",
			Handler:    _TradeServer_TradeOrderUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto/trade.proto",
}
