// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: pb/proto/trade.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskToken string `protobuf:"bytes,1,opt,name=TaskToken,proto3" json:"TaskToken,omitempty"`
	ReqTime   string `protobuf:"bytes,2,opt,name=ReqTime,proto3" json:"ReqTime,omitempty"`
}

func (x *TradeReq) Reset() {
	*x = TradeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_trade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeReq) ProtoMessage() {}

func (x *TradeReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_trade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeReq.ProtoReflect.Descriptor instead.
func (*TradeReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_trade_proto_rawDescGZIP(), []int{0}
}

func (x *TradeReq) GetTaskToken() string {
	if x != nil {
		return x.TaskToken
	}
	return ""
}

func (x *TradeReq) GetReqTime() string {
	if x != nil {
		return x.ReqTime
	}
	return ""
}

type TradeObtainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Obtain string `protobuf:"bytes,1,opt,name=Obtain,proto3" json:"Obtain,omitempty"`
	State  string `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *TradeObtainReq) Reset() {
	*x = TradeObtainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_trade_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeObtainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeObtainReq) ProtoMessage() {}

func (x *TradeObtainReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_trade_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeObtainReq.ProtoReflect.Descriptor instead.
func (*TradeObtainReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_trade_proto_rawDescGZIP(), []int{1}
}

func (x *TradeObtainReq) GetObtain() string {
	if x != nil {
		return x.Obtain
	}
	return ""
}

func (x *TradeObtainReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type TradeOnceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeOrderId    string `protobuf:"bytes,1,opt,name=TradeOrderId,proto3" json:"TradeOrderId,omitempty"`
	PayOrderId      string `protobuf:"bytes,2,opt,name=PayOrderId,proto3" json:"PayOrderId,omitempty"`
	CarbonAssetId   string `protobuf:"bytes,3,opt,name=CarbonAssetId,proto3" json:"CarbonAssetId,omitempty"`
	ExchangeAssetId string `protobuf:"bytes,4,opt,name=ExchangeAssetId,proto3" json:"ExchangeAssetId,omitempty"`
	Initiator       string `protobuf:"bytes,5,opt,name=Initiator,proto3" json:"Initiator,omitempty"`
	Number          int64  `protobuf:"varint,6,opt,name=Number,proto3" json:"Number,omitempty"`
	Recipient       string `protobuf:"bytes,7,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	TadeStatus      int64  `protobuf:"varint,8,opt,name=TadeStatus,proto3" json:"TadeStatus,omitempty"`
	InitiatorTime   string `protobuf:"bytes,9,opt,name=InitiatorTime,proto3" json:"InitiatorTime,omitempty"`
	FinishTime      string `protobuf:"bytes,10,opt,name=FinishTime,proto3" json:"FinishTime,omitempty"`
}

func (x *TradeOnceResp) Reset() {
	*x = TradeOnceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_trade_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeOnceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOnceResp) ProtoMessage() {}

func (x *TradeOnceResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_trade_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOnceResp.ProtoReflect.Descriptor instead.
func (*TradeOnceResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_trade_proto_rawDescGZIP(), []int{2}
}

func (x *TradeOnceResp) GetTradeOrderId() string {
	if x != nil {
		return x.TradeOrderId
	}
	return ""
}

func (x *TradeOnceResp) GetPayOrderId() string {
	if x != nil {
		return x.PayOrderId
	}
	return ""
}

func (x *TradeOnceResp) GetCarbonAssetId() string {
	if x != nil {
		return x.CarbonAssetId
	}
	return ""
}

func (x *TradeOnceResp) GetExchangeAssetId() string {
	if x != nil {
		return x.ExchangeAssetId
	}
	return ""
}

func (x *TradeOnceResp) GetInitiator() string {
	if x != nil {
		return x.Initiator
	}
	return ""
}

func (x *TradeOnceResp) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *TradeOnceResp) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *TradeOnceResp) GetTadeStatus() int64 {
	if x != nil {
		return x.TadeStatus
	}
	return 0
}

func (x *TradeOnceResp) GetInitiatorTime() string {
	if x != nil {
		return x.InitiatorTime
	}
	return ""
}

func (x *TradeOnceResp) GetFinishTime() string {
	if x != nil {
		return x.FinishTime
	}
	return ""
}

type TradeListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeOnceResp []*TradeOnceResp `protobuf:"bytes,1,rep,name=TradeOnceResp,proto3" json:"TradeOnceResp,omitempty"`
}

func (x *TradeListResp) Reset() {
	*x = TradeListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_trade_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeListResp) ProtoMessage() {}

func (x *TradeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_trade_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeListResp.ProtoReflect.Descriptor instead.
func (*TradeListResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_trade_proto_rawDescGZIP(), []int{3}
}

func (x *TradeListResp) GetTradeOnceResp() []*TradeOnceResp {
	if x != nil {
		return x.TradeOnceResp
	}
	return nil
}

type TradeExecutionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeOrderId string `protobuf:"bytes,1,opt,name=TradeOrderId,proto3" json:"TradeOrderId,omitempty"`
	Status       int32  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	CreateTime   string `protobuf:"bytes,3,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
}

func (x *TradeExecutionResp) Reset() {
	*x = TradeExecutionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_trade_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeExecutionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeExecutionResp) ProtoMessage() {}

func (x *TradeExecutionResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_trade_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeExecutionResp.ProtoReflect.Descriptor instead.
func (*TradeExecutionResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_trade_proto_rawDescGZIP(), []int{4}
}

func (x *TradeExecutionResp) GetTradeOrderId() string {
	if x != nil {
		return x.TradeOrderId
	}
	return ""
}

func (x *TradeExecutionResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TradeExecutionResp) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type TradeOrderUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayOrderId  string `protobuf:"bytes,1,opt,name=PayOrderId,proto3" json:"PayOrderId,omitempty"`
	Amount      string `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	UpdateState int64  `protobuf:"varint,3,opt,name=UpdateState,proto3" json:"UpdateState,omitempty"`
}

func (x *TradeOrderUpdateReq) Reset() {
	*x = TradeOrderUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_trade_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeOrderUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOrderUpdateReq) ProtoMessage() {}

func (x *TradeOrderUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_trade_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOrderUpdateReq.ProtoReflect.Descriptor instead.
func (*TradeOrderUpdateReq) Descriptor() ([]byte, []int) {
	return file_pb_proto_trade_proto_rawDescGZIP(), []int{5}
}

func (x *TradeOrderUpdateReq) GetPayOrderId() string {
	if x != nil {
		return x.PayOrderId
	}
	return ""
}

func (x *TradeOrderUpdateReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TradeOrderUpdateReq) GetUpdateState() int64 {
	if x != nil {
		return x.UpdateState
	}
	return 0
}

type TradeOrderUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *TradeOrderUpdateResp) Reset() {
	*x = TradeOrderUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_trade_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeOrderUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOrderUpdateResp) ProtoMessage() {}

func (x *TradeOrderUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_trade_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOrderUpdateResp.ProtoReflect.Descriptor instead.
func (*TradeOrderUpdateResp) Descriptor() ([]byte, []int) {
	return file_pb_proto_trade_proto_rawDescGZIP(), []int{6}
}

func (x *TradeOrderUpdateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_proto_trade_proto protoreflect.FileDescriptor

var file_pb_proto_trade_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x42, 0x0a, 0x08, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3e,
	0x0a, 0x0e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x4f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x4f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0xdd,
	0x02, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x22, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x61, 0x72,
	0x62, 0x6f, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x45, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x64, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x54, 0x61,
	0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x48,
	0x0a, 0x0d, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x37, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0d, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x70, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22,
	0x0a, 0x0c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x6f, 0x0a, 0x13, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc9, 0x01,
	0x0a, 0x0b, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3b, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x62,
	0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0e, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x72, 0x61, 0x64, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x45, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_proto_trade_proto_rawDescOnce sync.Once
	file_pb_proto_trade_proto_rawDescData = file_pb_proto_trade_proto_rawDesc
)

func file_pb_proto_trade_proto_rawDescGZIP() []byte {
	file_pb_proto_trade_proto_rawDescOnce.Do(func() {
		file_pb_proto_trade_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_trade_proto_rawDescData)
	})
	return file_pb_proto_trade_proto_rawDescData
}

var file_pb_proto_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_proto_trade_proto_goTypes = []interface{}{
	(*TradeReq)(nil),             // 0: pb.TradeReq
	(*TradeObtainReq)(nil),       // 1: pb.TradeObtainReq
	(*TradeOnceResp)(nil),        // 2: pb.TradeOnceResp
	(*TradeListResp)(nil),        // 3: pb.TradeListResp
	(*TradeExecutionResp)(nil),   // 4: pb.TradeExecutionResp
	(*TradeOrderUpdateReq)(nil),  // 5: pb.TradeOrderUpdateReq
	(*TradeOrderUpdateResp)(nil), // 6: pb.TradeOrderUpdateResp
}
var file_pb_proto_trade_proto_depIdxs = []int32{
	2, // 0: pb.TradeListResp.TradeOnceResp:type_name -> pb.TradeOnceResp
	1, // 1: pb.TradeServer.GetTradeObtainList:input_type -> pb.TradeObtainReq
	0, // 2: pb.TradeServer.TradeExecution:input_type -> pb.TradeReq
	5, // 3: pb.TradeServer.TradeOrderUpdate:input_type -> pb.TradeOrderUpdateReq
	3, // 4: pb.TradeServer.GetTradeObtainList:output_type -> pb.TradeListResp
	4, // 5: pb.TradeServer.TradeExecution:output_type -> pb.TradeExecutionResp
	6, // 6: pb.TradeServer.TradeOrderUpdate:output_type -> pb.TradeOrderUpdateResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_proto_trade_proto_init() }
func file_pb_proto_trade_proto_init() {
	if File_pb_proto_trade_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_trade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_trade_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeObtainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_trade_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeOnceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_trade_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_trade_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeExecutionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_trade_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeOrderUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_trade_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeOrderUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_trade_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_proto_trade_proto_goTypes,
		DependencyIndexes: file_pb_proto_trade_proto_depIdxs,
		MessageInfos:      file_pb_proto_trade_proto_msgTypes,
	}.Build()
	File_pb_proto_trade_proto = out.File
	file_pb_proto_trade_proto_rawDesc = nil
	file_pb_proto_trade_proto_goTypes = nil
	file_pb_proto_trade_proto_depIdxs = nil
}
